### ISSUE TITLE
"DeLong's test should not be applied to ROC curves with a different direction"

### ISSUE THREAD

**Issue by obruck** [xrobin/pROC#22] opened 2017-10-11 16:10 UTC
Hi!

I am computing ROC curves to compare a new score to previously developed scores. Visually when looking at AUROC curves, the new score seems to outperfom all old scores. One of the old scores performs quite bad and reminds the letter S (AUC = 0.52 and half of the curve is under the line of identity and the other half is ontop of the line of identity). I receive an error message when trying to analysis it with Delong's test

roc.test(score_new, score_old_3, method = "delong")

"Warning message:
In roc.test.roc(score_new, score_old_3, method = "delong") :
  DeLong's test should not be applied to ROC curves with a different direction."

According to Delong's test the new score is better than other scores (p<0.05), but with this bad-performing score_old_3, the p-value is 0.08. The problem remains with bootstrap and venkatraman. I do not thrust the results. How would you recommend me to analyze this?

Thanks for the help,
Oscar

**Comment by xrobin** [comment] 2017-10-11 16:27
Can you please provide a reproducible example and clarify what output you were expecting?

**Comment by obruck** [comment] 2017-10-11 16:39
Hi!

Thanks for the fast reply.

The data is attached. I am expecting to see that the AUROC of score_new is superior in terms of p-value than the score_old_2 and score_old_3. The variable status is the endpoint.

[a.xlsx](https://github.com/xrobin/pROC/files/1376456/a.xlsx)

**Comment by xrobin** [comment] 2017-10-11 17:14
Please clarify, what p-value were you expecting exactly? Or is this a request to handle ROC curves with different `direction` arguments in delong.test?

**Comment by obruck** [comment] 2017-10-11 17:52
With score_new vs. score_old_3 I am expecting a p-value<0.05, but I receive the error message. So should I use another test or could I compute this Delong somehow?

However, I do not thrust the results of the script below.

auroc <- read.csv("a.csv", header=TRUE)
score_old_3 <- roc(response = auroc$endpoint, predictor = auroc$score_old_3)
score_new <- roc(response = auroc$endpoint, predictor = auroc$score_new)
roc.test(score_new, score_old_3, method = "delong")

**Comment by xrobin** [comment] 2017-10-12 08:10
I cannot reproduce. Both `score_old_3` and `score_new` have the same direction (`<`) and I get a p=0.02 and no warning.

What versions of R and pROC are you using? Please post the output of `packageDescription("pROC")` and `sessionInfo()`

See the full transcript of what I am getting below. How does it differ from yours?

```
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(xlsx)
Loading required package: rJava
Loading required package: xlsxjars
> auroc <- read.xlsx("a.xlsx", 1)
> 
> library(pROC)
Type 'citation("pROC")' for a citation.

Attaching package: ‘pROC’

The following objects are masked from ‘package:stats’:

    cov, smooth, var

> score_old_3 <- roc(response = auroc$endpoint, predictor = auroc$score_old_3)
> print(score_old_3)

Call:
roc.default(response = auroc$endpoint, predictor = auroc$score_old_3)

Data: auroc$score_old_3 in 9 controls (auroc$endpoint 0) < 47 cases (auroc$endpoint 1).
Area under the curve: 0.5662
> score_new <- roc(response = auroc$endpoint, predictor = auroc$score_new)
> print(score_new)

Call:
roc.default(response = auroc$endpoint, predictor = auroc$score_new)

Data: auroc$score_new in 9 controls (auroc$endpoint 0) < 47 cases (auroc$endpoint 1).
Area under the curve: 0.8487
> roc.test(score_new, score_old_3, method = "delong")

	DeLong's test for two correlated ROC curves

data:  score_new and score_old_3
Z = 2.3215, p-value = 0.02026
alternative hypothesis: true difference in AUC is not equal to 0
sample estimates:
AUC of roc1 AUC of roc2 
  0.8486998   0.5661939 
```

**Comment by xrobin** [comment] 2017-10-31 07:38
In the absence of feedback I am closing this bug. Please feel free to reopen this issue if the problem still persists and you can provide additional information that could help reproduce it.

**Closed by xrobin** 2017-10-31 07:38 UTC
