### ISSUE TITLE
Print issue of roc-class object when a formula object is used for creating roc.

### ISSUE THREAD

**Issue by NielsKrarup** [xrobin/pROC#101] opened 2021-12-28 09:00 UTC
**Describe the bug**
If one programmatically creates formulas using stats::formula or as.formula, when using this in roc(formula=) argument, a print is not able of the resulting roc object.

It seems that this has to do with some non standard evaluation of the argument formula. which is triggered in the method print.dataline() see below rep.ex 

**To Reproduce**
set.seed(123)
df <- data.frame(y = rnorm(10), aval = sample(c(TRUE, FALSE), 10, replace = T))
form <- as.formula("aval ~ y")
roc.obj  <- pROC::roc(formula = form, data = df)
print(roc.obj)

#where it fails in print.dataline()
x <- roc.obj
predictor.name <- attr(terms(as.formula(x$call$formula), 
                             data = x$data), "term.labels")

**Comment by xrobin** [comment] 2021-12-28 15:32
Thanks for the report and the reproducible example. Indeed because the formula is passed as a variable name it seems to be breaking the `terms` call in `print.dataline`. 
I'm not entirely sure how to best fix it at this point. I'll give it some more thought to do it properly.

**Comment by xrobin** [comment] 2022-01-02 16:21
I investigated a fix where I would make the `print` function better at getting the data from the global environment.

But I'm running into trouble with stuff like

    form <- as.formula("aval ~ y")
    with(df, roc(form))

where the data is gone from the environment by the time `print` is called.

I'm getting all the data for `print.dataline` when I build the `roc` object within the `roc` function, so the proper fix will be to save it in the object. It will however require a major version release, as the objects will be incompatible.

**Comment by NielsKrarup** [comment] 2022-01-02 17:47
Dear Robin

Thank you for looking into this - I have used pROC a lot and also did not
see any slick way of solving it. Your method sounds like a good solution.
Im surprised the issue has not been brought up before, as many must use
roc() programmatically, or maybe that is exactly why - since one mainly
like to print roc objects for initial exploratory analysis.

Thanks you for taking it up, and for a nice package.

br, Niels

Den søn. 2. jan. 2022 kl. 17.21 skrev Xavier Robin ***@***.***

**Comment by xrobin** [comment] 2022-07-16 16:02
This should be fixed on master now, and will be included in the next release.
I still need to investigate the issue with the `with` case - might need an other issue.

**Closed** 2023-06-26 07:53 UTC
Labels: bug
