### ISSUE TITLE
pRoc does not react on options(OutDec=",") in plot()

### ISSUE THREAD

**Issue by yurasmol** [xrobin/pROC#104] opened 2022-05-04 13:13 UTC
library(pROC)
options(OutDec=",")
roc <- roc(aSAH$outcome, aSAH$wfns, quiet=T)
plot(roc, print.thres="best", print.auc=T)
[Rplots.pdf](https://github.com/xrobin/pROC/files/8620602/Rplots.pdf)

**Comment by xrobin** [comment] 2022-07-16 12:20
Duplicate of #103.

**Closed by xrobin** 2022-07-16 12:20 UTC
